steps:
- task: NodeTool@0
  displayName: Use Node 8.11.3
  inputs:
    versionSpec: 8.11.3

- task: Npm@1
  displayName: npm install
  inputs:
    workingDir: remote
    verbose: false

- task: CopyFiles@2
  displayName: Copy Node Executable
  inputs:
    SourceFolder: '/opt/hostedtoolcache/node/8.11.3/x64/bin'
    Contents: 'node'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/linux64-remote'

- task: CopyFiles@2
  displayName: Copy Node Modules
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/remote'
    Contents: 'node_modules/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/linux64-remote'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/linux64-remote'
    ArtifactName: 'linux64-remote'